import { readFile, writeFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const reviewRules = JSON.parse(readFileSync('apps/assistant/skills/opm-standard-review/references/rules.json', 'utf8'));
const planDigest = (proposal: { baseToken: unknown; scope: unknown; command: unknown }) => createHash('sha256').update(JSON.stringify({ baseToken: proposal.baseToken, scope: proposal.scope, command: proposal.command })).digest('hex');

test.use({ baseURL: process.env.OPM_ASSISTANT_BASE ?? 'http://127.0.0.1:5177' });

test('一次需求实时生成完整咖啡图，结束统一确认，取消零写入并保存恢复', async ({ page }, info) => {
  test.setTimeout(480_000); test.skip(!process.env.OPM_ASSISTANT_PROOF, '需要独立助手测试项目');
  const proof = JSON.parse(await readFile(process.env.OPM_ASSISTANT_PROOF!, 'utf8'));
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1600, height: 1100 }); await page.goto(`/projects/${proof.projectId}`);
  await page.getByTestId('p02-create-model').click(); await page.getByTestId('ov02-model-name').fill(`实时整图验证-${Date.now()}`);
  await page.getByRole('button', { name: '创建并打开工作台', exact: true }).click();
  await expect(page.getByTestId('hs-save')).toBeEnabled(); await page.getByTestId('p03-bottom-toggle').click();
  if (await page.getByTestId('p03-right-panel-close').isVisible()) await page.getByTestId('p03-right-panel-close').click();
  await page.getByTestId('left-tab-assistant').click(); const panel = page.getByTestId('assistant-panel');
  const before = await page.getByTestId('hs-draft-identity').innerText();
  await panel.getByTestId('assistant-input').fill('帮我设计一个手工咖啡的 OPM 流程图，包含咖啡豆、咖啡粉、咖啡饮品，以及磨豆、冲泡两个过程，明确投入和产出关系。采用合理布局，直接完整生成，最后统一确认。');
  await panel.getByTestId('assistant-send').click(); await expect(panel.getByTestId('assistant-running')).toBeVisible();
  await expect(page.getByTestId('assistant-canvas-preview')).toContainText('实时生成预览', { timeout: 120_000 });
  await expect.poll(() => page.locator('.x6-node').count(), { timeout: 120_000 }).toBeGreaterThanOrEqual(2);
  await expect(panel.getByTestId('assistant-running')).toBeVisible(); await expect(panel.getByTestId('assistant-apply')).toBeDisabled();
  expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(before);
  await page.screenshot({ path: info.outputPath('assistant-live-progress.png') });
  await expect(panel.getByTestId('assistant-running')).toHaveCount(0, { timeout: 180_000 });
  await expect(panel.getByTestId('assistant-proposal')).toHaveCount(1); await expect(panel.getByTestId('assistant-apply')).toBeEnabled();
  await expect(panel.getByTestId('assistant-apply')).toHaveText('确认整图修改');
  await expect(panel.getByTestId('assistant-preview')).toHaveCount(0);
  for (const name of ['咖啡豆', '咖啡粉', '咖啡饮品', '磨豆', '冲泡']) await expect(page.locator('.x6-node').filter({ has: page.locator('text', { hasText: new RegExp(`^${name}$`) }) })).toBeVisible();
  expect(await page.locator('.x6-edge').count()).toBeGreaterThanOrEqual(4);
  expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(before);
  await page.screenshot({ path: info.outputPath('assistant-live-complete.png') });
  const modelId = new URL(page.url()).pathname.match(/\/models\/([^/]+)\/workbench/)![1];
  const contextId = (await page.getByTestId('opd-navigator').locator('[aria-current="page"]').getAttribute('data-testid'))!.replace('p03-context-', '');
  const scope = { projectId: proof.projectId, modelId, contextId };
  const session = await page.evaluate(() => window.__OPM_LOCAL_SESSION__);
  const post = async (op: string, extra: Record<string, unknown> = {}) => page.request.post(`/api/assistant/${op}`, { headers: { Origin: new URL(page.url()).origin, 'X-OPM-Session': session! }, data: { ...scope, ...extra } });
  let listed = await (await post('list')).json(); let plan = listed[0].proposals[0];
  expect(plan.command.command_type).toBe('APPLY_MODEL_PLAN'); expect(plan.command.payload.steps.length).toBeGreaterThanOrEqual(9);
  expect(plan.command.payload.steps.filter((step: { capability_id?: string }) => step.capability_id === 'CAP-ISO-PROC-001').length).toBeGreaterThanOrEqual(2);
  expect(plan.command.payload.steps.filter((step: { capability_id?: string }) => step.capability_id === 'CAP-ISO-PROC-002').length).toBeGreaterThanOrEqual(2);
  expect(plan.validation.validation_scope).toBe('MODEL'); expect(plan.validation.validation_summary.blocking).toBe(0);
  expect(plan.review.checks).toHaveLength(reviewRules.rules.length);
  expect(plan.review.skill_version).toBe(reviewRules.skill_version); expect(plan.review.source_digest).toBe(reviewRules.source.sha256);
  expect(plan.review.plan_digest).toBe(planDigest(plan)); expect(plan.review.issues.filter((issue: { severity: string }) => issue.severity === 'ERROR')).toEqual([]);
  await panel.getByTestId('assistant-standard-review').locator('summary').click();
  await expect(panel.getByTestId('assistant-standard-review')).toContainText('部分条款审查');
  await expect(panel.getByTestId('assistant-validation')).toContainText('当前规则通过');
  await page.screenshot({ path: info.outputPath('assistant-standard-review.png') });
  const initialReviewDigest = plan.review.plan_digest;
  expect(plan.quality.guide_version).toBe('1.0.0'); expect(plan.quality.plan_digest).toBe(planDigest(plan));
  await expect(panel.getByTestId('assistant-quality')).toContainText('建议不影响确认');
  const initialQualityDigest = plan.quality.plan_digest;
  const stableIds = plan.previewData.constructs.map((item: { occurrence_id: string }) => item.occurrence_id);
  await panel.getByTestId('assistant-input').fill('先不确认，把未提交预览中的咖啡饮品改名为手工咖啡，保留已有全部对象、过程和关系。');
  await panel.getByTestId('assistant-send').click(); await expect(panel.getByTestId('assistant-running')).toBeVisible();
  await expect(panel.getByTestId('assistant-running')).toHaveCount(0, { timeout: 120_000 });
  listed = await (await post('list')).json(); plan = listed[0].proposals.at(-1);
  expect(plan.review.plan_digest).toBe(planDigest(plan)); expect(plan.review.plan_digest).not.toBe(initialReviewDigest);
  expect(plan.review.checks).toHaveLength(reviewRules.rules.length); expect(plan.validation.validation_summary.blocking).toBe(0);
  expect(plan.quality.plan_digest).toBe(planDigest(plan)); expect(plan.quality.plan_digest).not.toBe(initialQualityDigest);
  expect(plan.status).toBe('ready'); expect(listed[0].proposals[0].status).toBe('cancelled');
  expect(plan.previewData.constructs.map((item: { occurrence_id: string }) => item.occurrence_id)).toEqual(stableIds);
  await expect(page.locator('.x6-node').filter({ has: page.locator('text', { hasText: /^手工咖啡$/ }) })).toBeVisible();
  expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(before);
  await writeFile(info.outputPath('assistant-scope.json'), JSON.stringify({ ...scope, conversationId: listed[0].id }));
  await panel.getByTestId('assistant-apply').last().click(); await expect(page.getByTestId('hs-draft-identity')).not.toHaveText(before);
  await expect(page.getByTestId('assistant-canvas-preview')).toHaveCount(0);
  const opened = await page.request.post(`/api/v2/projects/${scope.projectId}/models/${scope.modelId}/draft/open`, { headers: { Origin: new URL(page.url()).origin, 'X-OPM-Session': session! }, data: { request_id: 'request.live.proof', context_id: contextId } });
  const token = (await opened.json()).draft_token; expect(token.edit_seq).toBe(1);
  expect((await post('apply', { conversationId: listed[0].id, proposalId: plan.id, draftToken: token })).status()).toBe(200);
  await page.getByRole('tab', { name: 'OPL / OPT' }).click(); await expect(page.getByTestId('p03-opl-sentence')).not.toHaveCount(0);
  await page.getByTestId('hs-save').click(); await expect(page.getByTestId('hs-save-state')).toHaveText('已手动保存');
  await page.reload(); await expect(page.getByTestId('hs-save')).toBeEnabled(); await page.getByTestId('left-tab-assistant').click();
  await expect(panel.getByTestId('assistant-proposal').last()).toContainText('已应用');
  const persisted = (await (await post('list')).json())[0].proposals.at(-1); expect(persisted.review).toEqual(plan.review);
  expect(persisted.validation).toEqual(plan.validation); expect(persisted.quality).toEqual(plan.quality);
  const savedIdentity = await page.getByTestId('hs-draft-identity').innerText();
  await panel.getByTestId('assistant-input').fill('给当前咖啡流程增加一个名为包装的过程，在 x=500,y=450，先让我看预览。');
  await panel.getByTestId('assistant-send').click(); await expect(panel.getByTestId('assistant-running')).toBeVisible();
  await expect(panel.getByTestId('assistant-running')).toHaveCount(0, { timeout: 120_000 });
  await expect(page.locator('.x6-node').filter({ has: page.locator('text', { hasText: /^包装$/ }) })).toBeVisible();
  await panel.getByTestId('assistant-cancel').last().click(); await expect(page.getByTestId('assistant-canvas-preview')).toHaveCount(0);
  await expect(page.locator('.x6-node').filter({ has: page.locator('text', { hasText: /^包装$/ }) })).toHaveCount(0);
  expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(savedIdentity);
  await panel.getByTestId('assistant-input').fill('连续添加20个独立设备对象，名称从设备1到设备20，每个都创建，先展示预览。');
  await panel.getByTestId('assistant-send').click(); await expect(panel.getByTestId('assistant-running')).toBeVisible();
  await expect(page.getByTestId('assistant-canvas-preview')).toContainText('实时生成预览', { timeout: 120_000 });
  await panel.getByTestId('assistant-stop').click(); await expect(panel.getByTestId('assistant-running')).toHaveCount(0, { timeout: 20_000 });
  await expect(page.getByTestId('assistant-canvas-preview')).toHaveCount(0);
  expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(savedIdentity);
  await panel.getByTestId('assistant-input').fill('只增加一个名为测试设备的对象，x=250,y=500。');
  await panel.getByTestId('assistant-send').click(); await expect(panel.getByTestId('assistant-running')).toBeVisible();
  await expect(panel.getByTestId('assistant-running')).toHaveCount(0, { timeout: 120_000 });
  const stale = (await (await post('list')).json())[0].proposals.at(-1); expect(stale.status).toBe('ready');
  await page.getByTestId('p03-tool-object').click(); await expect(page.getByTestId('hs-draft-identity')).not.toHaveText(savedIdentity);
  const manualIdentity = await page.getByTestId('hs-draft-identity').innerText();
  expect((await post('apply', { conversationId: listed[0].id, proposalId: stale.id, draftToken: stale.baseToken })).status()).toBe(409);
  expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(manualIdentity);
  await page.setViewportSize({ width: 390, height: 844 }); await panel.scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('assistant-live-mobile.png') }); expect(errors).toEqual([]);
});

test('服务重启后恢复整图记录和同一会话，读取解释不改模型', async ({ page }) => {
  test.setTimeout(120_000); test.skip(!process.env.OPM_ASSISTANT_LIVE_RESUME_PROOF, '需要实时整图用例输出的隔离模型身份');
  const scope = JSON.parse(await readFile(process.env.OPM_ASSISTANT_LIVE_RESUME_PROOF!, 'utf8'));
  await page.goto(`/projects/${scope.projectId}/models/${scope.modelId}/workbench?context=${scope.contextId}`);
  await expect(page.getByTestId('hs-save')).toBeEnabled(); await page.getByTestId('left-tab-assistant').click();
  const panel = page.getByTestId('assistant-panel'); await expect(panel.getByTestId('assistant-input')).toBeEnabled();
  const session = await page.evaluate(() => window.__OPM_LOCAL_SESSION__);
  const listed = await page.request.post('/api/assistant/list', { headers: { Origin: new URL(page.url()).origin, 'X-OPM-Session': session! }, data: scope });
  const history = (await listed.json())[0]; expect(history.id).toBe(scope.conversationId);
  expect(history.proposals.some((proposal: { status: string }) => proposal.status === 'applied')).toBe(true);
  const applied = history.proposals.find((proposal: { status: string }) => proposal.status === 'applied');
  expect(applied.quality.plan_digest).toBe(planDigest(applied));
  expect(applied.review.checks).toHaveLength(reviewRules.rules.length); expect(applied.review.plan_digest).toBe(planDigest(applied));
  await expect(page.locator('.x6-node').filter({ has: page.locator('text', { hasText: /^手工咖啡$/ }) })).toBeVisible();
  const before = await page.getByTestId('hs-draft-identity').innerText();
  await panel.getByTestId('assistant-input').fill('只读取解释已经确认的手工咖啡流程，包括磨豆和冲泡，不提出任何修改。');
  await panel.getByTestId('assistant-send').click(); await expect(panel.getByTestId('assistant-running')).toBeVisible();
  await expect(panel.getByTestId('assistant-running')).toHaveCount(0, { timeout: 90_000 });
  await expect(panel.locator('.assistant-message--assistant').last()).toContainText('磨豆');
  await expect(panel.locator('.assistant-message--assistant').last()).toContainText('冲泡');
  expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(before);
});
