import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";

test.use({ baseURL: process.env.OPM_ASSISTANT_BASE ?? "http://127.0.0.1:5177" });

test("编辑错误问题后真实 DeepSeek 提出更正模型，图标显示及保存恢复正常", async ({ page }, info) => {
  test.setTimeout(240_000);
  test.skip(!process.env.OPM_ASSISTANT_PROOF, "需要独立助手测试项目，禁止复用用户模型");
  const scope = JSON.parse(await readFile(process.env.OPM_ASSISTANT_PROOF!, "utf8"));
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto(`/projects/${scope.projectId}`); await page.getByTestId('p02-create-model').click();
  await page.getByTestId('ov02-model-name').fill(`助手纠错验证-${Date.now()}`);
  await page.getByRole('button', { name: '创建并打开工作台', exact: true }).click();
  await expect(page.getByTestId('hs-save')).toBeEnabled(); await page.getByTestId('left-tab-assistant').click();
  const panel = page.getByTestId('assistant-panel'), input = panel.getByTestId('assistant-input');
  const original = '只解释“手工开发”作为过程的含义，不修改模型，也不提出修改提案。';
  await input.fill(original); await panel.getByTestId('assistant-send').click();
  await expect(panel.getByTestId('assistant-running')).toBeVisible();
  await expect(panel.getByTestId('assistant-edit-message').first()).toBeDisabled();
  await expect(panel.getByTestId('assistant-running')).toHaveCount(0, { timeout: 120_000 });
  await expect(panel.locator('.assistant-message--assistant')).toHaveCount(1);
  await expect(panel.getByTestId('assistant-proposal')).toHaveCount(0);
  const identity = await page.getByTestId('hs-draft-identity').innerText();
  await input.fill('未发送草稿'); await panel.getByTestId('assistant-edit-message').first().click();
  await expect(input).toHaveValue(original); await expect(input).toBeFocused();
  await input.fill('取消的更正'); await panel.getByTestId('assistant-edit-cancel').click();
  await expect(input).toHaveValue('未发送草稿'); expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(identity);
  await panel.getByTestId('assistant-edit-message').first().click();
  await input.fill('我输入错了，要建模手工咖啡。创建名为手工咖啡的过程，x=400,y=180。只提出这个过程的一个修改提案，先不应用。');
  await expect(panel.getByTestId('assistant-send')).toHaveText('发送更正');
  await page.screenshot({ path: info.outputPath('assistant-edit-desktop.png') });
  await panel.getByTestId('assistant-send').click();
  await expect(panel.getByTestId('assistant-running')).toBeVisible();
  await expect(panel.getByTestId('assistant-running')).toHaveCount(0, { timeout: 120_000 });
  await expect(input).toHaveValue('未发送草稿');
  await expect(panel.locator('.assistant-message--user')).toHaveCount(2);
  await expect(panel.locator('.assistant-message--user p').first()).toHaveText(original);
  await expect(panel.locator('.assistant-message--user p').last()).toContainText('更正我之前的问题');
  await expect(panel.getByTestId('assistant-proposal')).toHaveCount(1);
  await expect(panel.getByTestId('assistant-proposal')).toContainText('手工咖啡');
  expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(identity);
  if (await panel.getByTestId('assistant-preview').isVisible()) await panel.getByTestId('assistant-preview').click();
  const processNode = page.locator('.x6-node').filter({ has: page.locator('text', { hasText: /^手工咖啡$/ }) });
  await expect(processNode).toBeVisible(); expect(await page.getByTestId('hs-draft-identity').innerText()).toBe(identity);
  await panel.getByTestId('assistant-apply').click();
  await expect(page.getByTestId('hs-draft-identity')).not.toHaveText(identity); await expect(processNode).toBeVisible();
  await expect(panel.locator('.assistant-message--user .assistant-avatar').first()).toHaveAttribute('aria-label', '用户');
  await expect(panel.locator('.assistant-message--assistant .assistant-avatar').first()).toHaveAttribute('aria-label', '智能助手');
  await expect(panel.locator('.assistant-message__header strong')).toHaveCount(0);
  await page.getByTestId('hs-save').click(); await expect(page.getByTestId('hs-save-state')).toHaveText('已手动保存');
  await page.reload(); await expect(page.getByTestId('hs-save')).toBeEnabled(); await expect(processNode).toBeVisible();
  await page.getByTestId('left-tab-assistant').click(); await expect(panel.locator('.assistant-message--user')).toHaveCount(2);
  await panel.getByTestId('assistant-edit-message').first().click();
  await page.setViewportSize({ width: 390, height: 844 }); await panel.scrollIntoViewIfNeeded();
  const box = (await panel.boundingBox())!; expect(box.x + box.width).toBeLessThanOrEqual(391);
  await expect(input).toBeVisible(); await expect(panel.getByTestId('assistant-edit-cancel')).toBeVisible();
  await page.screenshot({ path: info.outputPath('assistant-edit-mobile.png') });
  await panel.getByTestId('assistant-edit-cancel').click();
  expect(errors).toEqual([]);
});
