package org.opm.localruntime.api;

public enum ApiErrorCode {
    INVALID_ARGUMENT,
    NOT_FOUND,
    IDEMPOTENCY_MISMATCH,
    REVISION_CONFLICT,
    READ_ONLY_REVISION,
    RULE_VERSION_CONFLICT,
    PROFILE_FORBIDDEN,
    DOMAIN_REJECTED,
    VALIDATION_BLOCKED,
    MODIFIER_COMBINATION_INVALID,
    TEXT_GENERATION_BLOCKED,
    PERSISTENCE_FAILED,
    TASK_FAILED,
    LOCAL_SESSION_INVALID
}
