package org.opm.localruntime.semantic;

public enum SemanticValidationCode {
    DUPLICATE_ID,
    MISSING_REFERENCE,
    CAPABILITY_BINDING_MISMATCH,
    INVALID_ENDPOINT,
    STATE_OWNER_MISMATCH,
    INVALID_STATE_PRESENTATION,
    CONTEXT_CLOSURE_VIOLATION,
    INVALID_LAYOUT,
    INVALID_OWNERSHIP
}
