package org.opm.localruntime.text;

public enum OplGenerationCode {
    MODIFIER_COMBINATION_INVALID,
    ENDPOINT_KIND_MISMATCH,
    STATE_OWNER_MISMATCH,
    TEXT_PRODUCTION_IDENTITY_INVALID,
    TEXT_PLAN_UNSUPPORTED,
    TEXT_CAPABILITY_UNSUPPORTED,
    TEXT_TEMPLATE_MISSING,
    TEXT_GRAMMAR_BINDING_MISMATCH,
    TEXT_COMPOSITION_FAILED,
    TEXT_TRACE_INCOMPLETE,
    TEXT_LEGACY_VALUE_FORBIDDEN,
    INVALID_ARGUMENT
}
